name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clone VCIM repository
        run: |
            git clone https://github.com/play-go/vcim.git vcim_main

      - name: Install Dependencies
        run: |
            cd vcim_main
            python -m pip install --upgrade pip
            python -m pip install nuitka zstandard
            python -m pip install -r requirements.txt

      - name: Build Fast VCIM EXE
        run: |
            cd vcim_main
            python -m nuitka --standalone --onefile --mingw64 --assume-yes-for-downloads vcim.py

      - name: Zip VCIM executable
        shell: pwsh
        run: |
            Compress-Archive -Path vcim_main/vcim.exe -DestinationPath vcim_fast.zip

      - name: Upload VCIM ZIP
        uses: actions/upload-artifact@v4
        with:
          name: vcim-fast-exe
          path: vcim_fast.zip

      - name: Build with Maven
        run: mvn clean compile

      - name: Package JAR
        run: mvn package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Orbis
          path: target/*.jar